import = [
    "~/.config/alacritty/gruvbox_theme/gruvbox_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 20
padding.y = 20
decorations = "Buttonless"
opacity = 1
blur = true

[bell]
animation = "EaseOutExpo"
duration = 0

[font]
normal.family = "Hack Nerd Font"
size = 18.0

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
  {key = "T", mods = "Command", action = "None"},
  {key = "N", mods = "Command", action = "None"},
  {key = "W", mods = "Command", action = "Quit"},
  {key = "F", mods = "Option", action = "ToggleFullscreen"},
]
